### ISSUE TITLE
Enum type is broken

### ISSUE THREAD

**Issue by zeddidragon** [devmynd/jsonb_accessor#38]
```ruby
class Example < ActiveRecord::Base
  enum coffee: {black: 0, white: 1, tea: 2}
  jsonb_accessor :preferences, coffee: :enum
end

Example.new(coffee: :black)   # ArgumentError: '0' is not a valid game_type

example = Example.new
example.coffee = :black
example.coffee  # nil
```

If I declare the enum after the jsonb_accessor, ```Example.new(coffee: black)``` also leaves coffee as nil.

**Comment by jhirn** [comment]
I'm not sure if we want to support enums directly since as far as the database knows, they are integers (or strings). [Postgres does have the concept of enums](http://www.postgresql.org/docs/9.5/static/functions-enum.html), but they don't map to what ActiveRecord does. It would actually require a migration to generate them as and I'm they aren't natively supported by Json. It would make the data unportable. 

I can't think of a generic enough implementation for this gem to cover all cases. I'm open to more discussion on how to support enums but my recommendation would be to store them as integer or string types.
