### ISSUE TITLE
overriding jsonb attributes setter can lead to potential problems

### ISSUE THREAD

**Issue by wow-sweetlie** [devmynd/jsonb_accessor#63]
Hi, let me present my jsonb use case to set some context
- I'm retrieving json from external api call. The jsonb is great for me as I don't know how api may elvolve and I don't have to describe each field. Nevertheless I am sure of the presence of some attributes and jsonb_acessor / store_accessor could be a great help to make the code look nicer or even add some constraints I can rely on in spite of potential api changes.

I've seen some potential issues in the way jsonb attributes setter is overrided
- This code should not be where accessor are keeped in sync. What if jsonb field is modified without using the setter ? The attribute getter should instead always return a value from the jsonb field

- There's too much interference between accessors / and jsonb contents : 
  * setting default values is fine
  * value name -> store name field conversion is not intuitive and could lead to potential problems when you can't be sure of your json fields. Setter / getter should just be helpful shortcuts. default value is just a bonus. See this spec for what I'm talking about :
https://github.com/devmynd/jsonb_accessor/blob/master/spec/jsonb_accessor_spec.rb#L134

- With the current implementation I need to describe all the fields beacause of this line :
https://github.com/devmynd/jsonb_accessor/blob/master/lib/jsonb_accessor/macro.rb#L37

This gem as a good potential, I'll happily contribute to it, as my project is heavily relying on  jsonb fields.

**Comment by crismali** [comment]
Hi, thanks for using our gem! There's a lot here so let's look at it in pieces.

> This code should not be where accessor are keeped in sync. What if jsonb field is modified without using the setter ?

It's true that if it's modified without the setter things will likely get out of sync. This is part of the tradeoff of using ActiveRecord's `attribute` internally: It gives us the defaults, type coercion, dirty tracking, etc that make an ActiveRecord field feel like an ActiveRecord field for free aside from the potential out of sync problem when skipping a setter. Managing all of those things ourselves (as we've done in previous iterations of this gem) tend to create more problems. Plus I think with or without jsonb_accessor, skipping ActiveRecord's setter methods is a risky proposition anyway.

> value name -> store name field conversion is not intuitive and could lead to potential problems when you can't be sure of your json fields.

Absolutely, but a few things: First, this is behavior consumers of the gem opt into by using the store key feature. Second, having attribute names that differ from the key names they're stored at will always be more complex than if they were the same name. That's just part of the deal. 

> With the current implementation I need to describe all the fields

I think this is also part of the deal or else things get too dynamic, meta, and otherwise hard to understand very quickly. I'm happy to review any and all pull requests regarding this or any of the other issues you've raised here that improve the gem overall 👍 It's always harder to discuss these sorts of things in the abstract compared to actually seeing new code and how it address or creates certain tradeoffs.

Thanks for your feedback 👍 👍 I'm going to close this for now so we can take a look at each item more closely in their PRs.
