### ISSUE TITLE
How to dynamically call jsonb_accessor with class_eval

### ISSUE THREAD

**Issue by krsyoung** [devmynd/jsonb_accessor#86]
Hi, I'm trying to dynamically call `jsonb_accessor` as part of an ApplicationRecord's `after_initialize` method.  I am doing this because the actual values stored in the JSON are user defined.

I have this working using `store_accessor` however cannot get it to work with `jsonb_accessor`.  Curious if it *should* work and if anybody had ideas how to make it work.   Here is my code:

```
  after_initialize do
    # load parameters from user definition ... (i.e. :cost)

    # works
    singleton_class.class_eval { store_accessor :data, :cost }

    # does not work
    singleton_class.class_eval { jsonb_accessor :data, cost: :string }
  end
```

The error in my form indicates that I have a setter but not a getter:

```
undefined method `cost' for #<Component:0x007fcab2f53050>
Did you mean?  cost =
```

However, if I actually call the setter I get a different error:

```
>>  f.object.cost=100
NoMethodError: super: no superclass method `cost=' for #<Component:0x007fcab2f53050>
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activemodel-5.1.4/lib/active_model/attribute_methods.rb:429:in `method_missing'
	from /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jsonb_accessor-1.0.0/lib/jsonb_accessor/macro.rb:63:in `block (3 levels) in jsonb_accessor'
```

Any ideas greatly appreciated!

**Comment by crismali** [comment]
This is a complicated one, but basically JsonbAccessor works by defining attributes via the [attribute API](http://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute) and then overriding the getters and setters defined by it by mixing in a module. At first glance it looks like the attribute API isn't playing well with the singleton class, but I'm not sure. You may want to try just defining some attributes using the attribute api without JsonbAccessor and seeing if you can `super` up to them. My guess is that it's broken there, but if not at least we'll be pretty sure the problem is something we can handle in the gem.

**Comment by krsyoung** [comment]
Thanks for the ideas @crismali!  Seems like my particular use case isn't common / a pain point for other users.

In the meantime I've worked around things however I don't want to give-up on using `jsonb_accessor`.  Maybe I'll close this issue for now (your comment is perfect for future reference) and if I come back to it I'll update my response with what I managed to get working or a PR to any changes.

**Comment by kiddrew** [comment]
I have this exact use case and I just ran into the same error. @krsyoung did you ever find a solution using this gem?

**Comment by krsyoung** [comment]
Sorry @kiddrew, absolutely all of these brain cells are gone! I can't remember what project I was working on which is making it impossible to find my "workaround". BTW 👎 to my former self for not documenting the workaround in the issue.

**Comment by haffla** [comment]
@kiddrew you are right about `singleton_class`. It creates a new class for each object.
